### ISSUE TITLE
How to reproduce the result of other methods?

### ISSUE THREAD

**Issue by fengyuanyu1** [YangLin-George/PLELog#4]
Hello, Dr.Yang.
Some results of other researches which are not consistent with their original papers appear in your paper.
However, I find that there is no source code provided by their authors publicly. (Deeplog, LogAnomaly, LogRobust, and so on).
Can you tell me how to reproduce the result of other methods? 
I appreciate it If you can offer some source code or other efficient methods.

**Comment by YangLin-George** [comment]
Hi @Yuandaodao ,
Unfortunately, none of the compared methods have released their source code. But we are able to find re-implementations in GitHub.
For DeepLog, LogAnomaly and LogRobust, we use [logdeep](https://github.com/donglee-afar/logdeep) in our experiments.
Other methods such as PCA and LogClustering, please refer to [LogPAI](https://github.com/logpai/loglizer).
 
Since your are asking for the reproduction problem, please be noted that the experimental settings are different among all methods, so the inconsistency is somehow inevitable.

Thanks for your question, if you have any further questions, please let me know.
